In [8]:
import numpy as np
import pandas as pd
from itertools import product

In [ ]:
arr=np.array([1,2,3,4,5])
rev=arr[::-1]
print("Reversed array is ",rev)
arr1=np.array([[1,2,3],[2,4,5],[1,2,3]])
flat=arr1.flatten()
print(flat)

In [ ]:
ar1=np.array([[1,2],[3,4]])
ar2=np.array([[1,2],[3,4]])
if ar1==ar2:
    print('Same')

In [ ]:
x = np.array([1,2,3,4,5,1,2,1,1,1])
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])
modex=np.bincount(x).argmax()
print("Mode of array x ",x,"is",modex)
modey=np.bincount(y).argmax()
print("Mode of array x ",y,"is",modey)

In [ ]:
gfg=np.array([[4,1,9],[12,3,1],[4,5,6]])
print(np.sum(gfg))
print(np.sum(gfg,axis=0))
print(np.sum(gfg,axis=1))

In [ ]:
n_array=np.array([[55,25,15],[30,44,2],[11,45,77]])
print("Sum of diagonal elemnst is ", np.trace(n_array))
eigenval,eigenvec=np.linalg.eig(n_array)
print("Eigenvalues",eigenval)
print("Eigenvalues",eigenvec)
print("Inverse is ",np.linalg.inv(n_array))
print("determinant is ",mp.linalg.det(n_array))

In [3]:
p=np.array([[1,2],[3,4]])
q=np.array([[4,5],[6,7]])
print(p*q)
print(np.cov(p,q))

[[ 4 10]
 [18 28]]
[[0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]]


In [5]:
a=np.array([[1,2],[2,3],[4,5]])
b=np.array([[4,5,1],[6,7,2]])
print(np.dot(a*b))
print(np.cov(a,b))

ValueError: operands could not be broadcast together with shapes (3,2) (2,3) 

In [9]:
x=np.array([[2,3,4],[3,2,9]])
y=np.array([[1,5,0],[5,10,3]])
print(np.inner(x,y))
print(np.outer(x,y))
cartesian=np.array(list(product(x,y)))
print(cartesian)

[[17 52]
 [13 62]]
[[ 2 10  0 10 20  6]
 [ 3 15  0 15 30  9]
 [ 4 20  0 20 40 12]
 [ 3 15  0 15 30  9]
 [ 2 10  0 10 20  6]
 [ 9 45  0 45 90 27]]
[[[ 2  3  4]
  [ 1  5  0]]

 [[ 2  3  4]
  [ 5 10  3]]

 [[ 3  2  9]
  [ 1  5  0]]

 [[ 3  2  9]
  [ 5 10  3]]]


In [ ]:
array2=np.array([[1,-2,3],[-4,5,-6]])
flat2=array2.flatten()
print("Mean :",np.mean(flat2),"Median :",np.median(flat2),"SD :",np.std(flat2))
print("For column",np.percentile(array2,[25,50,75],axis=0))
print("For row",np.percentile(array2,[25,50,75],axis=1))
print(abs(array2))

In [ ]:
a=np.array([-1.8,-1.6,-0.5,0.5,1.6,1.8,3])
print("Ceil",np.ceil(a))
print("Ceil",np.floor(a))
print("Ceil",np.trunc(a))
print("Ceil",np.round(a))

In [ ]:
array3=np.array([10,52,62,16,16,54,453])
print(np.sort(array3))
print(array3.head(4))
print(array3.tail(5))


In [ ]:
array3=np.array([1,1.2,2.2,2,3,2])
integer=array3[array3==array3.astype(int)]
floats=array3[array3==array3.astype(float)]
print(intger)
print(floats)

In [ ]:
import cv2
image=cv2.imread("")
image_rgb=cv2.cvtColor(image,cv2.COLOR_BGR2RGB)
print(image_rgb)