In [1]:
import pandas as pd
import numpy as np

In [2]:
#Q1
dataset = pd.read_csv('C:/Users/Prabhsimrat Singh/Desktop/MLAI/S01 - Machine-Learning-A-Z-Codes-Datasets/archive/AWCustomers.csv')
#take CustomerID,Country,Gender,Marital status,homeowner flag,numbercarsowned,numberchildrenathome,totalchildren,yearlyincome
x = dataset.iloc[:, [0, 10,16, 17, 18, 19, 20, 21, 22]].values
print(x)

[[21173 'Australia' 'M' ... 0 1 81916]
 [13249 'Canada' 'M' ... 1 2 81076]
 [29350 'United States' 'F' ... 0 0 86387]
 ...
 [12160 'United States' 'F' ... 0 0 51859]
 [14353 'Canada' 'F' ... 0 0 87177]
 [16676 'United States' 'F' ... 0 0 136856]]


In [3]:
#Q2. A
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
x[:, -4:] = imputer.fit_transform(x[:, -4:])
# replace any null values in these columns with avergae: numbercarsowned,numberchildrenathome,totalchildren,yearlyincome

In [6]:
print(x)

[[21173 'Australia' 'M' ... 0.0 1.0 81916.0]
 [13249 'Canada' 'M' ... 1.0 2.0 81076.0]
 [29350 'United States' 'F' ... 0.0 0.0 86387.0]
 ...
 [12160 'United States' 'F' ... 0.0 0.0 51859.0]
 [14353 'Canada' 'F' ... 0.0 0.0 87177.0]
 [16676 'United States' 'F' ... 0.0 0.0 136856.0]]


In [7]:
#Q2. E
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
import numpy as np


#Country,Gender,Marital status,homeowner flag are categorivcal variables
ct = ColumnTransformer(
    transformers=[('encoder', OneHotEncoder(sparse_output=False), [1, 2, 3,4])],
    remainder='passthrough'
)

x_transformed = ct.fit_transform(x)  # returns dense array

#View as a DataFrame so it's easier to read
df_x = pd.DataFrame(x_transformed)
#print(x_transformed)

In [19]:
print(df_x)

        0    1    2    3    4    5    6    7    8    9    10   11     12   13  \
0      1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  1.0  0.0  0.0  1.0  21173  3.0   
1      0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  1.0  0.0  0.0  1.0  13249  2.0   
2      0.0  0.0  0.0  0.0  0.0  1.0  1.0  0.0  0.0  1.0  1.0  0.0  29350  3.0   
3      0.0  0.0  0.0  0.0  1.0  0.0  0.0  1.0  1.0  0.0  0.0  1.0  13503  2.0   
4      0.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  1.0  22803  1.0   
...    ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...    ...  ...   
18356  0.0  0.0  0.0  0.0  0.0  1.0  1.0  0.0  1.0  0.0  1.0  0.0  25414  1.0   
18357  1.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  1.0  1.0  0.0  11459  2.0   
18358  0.0  0.0  0.0  0.0  0.0  1.0  1.0  0.0  0.0  1.0  1.0  0.0  12160  2.0   
18359  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  1.0  1.0  0.0  14353  0.0   
18360  0.0  0.0  0.0  0.0  0.0  1.0  1.0  0.0  1.0  0.0  0.0  1.0  16676  2.0   

        14   15        16  

In [11]:
print(x[:,-4:])

[[3.0 0.0 1.0 81916.0]
 [2.0 1.0 2.0 81076.0]
 [3.0 0.0 0.0 86387.0]
 ...
 [2.0 0.0 0.0 51859.0]
 [0.0 0.0 0.0 87177.0]
 [2.0 0.0 0.0 136856.0]]


In [13]:
#Q2. D
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x[:,-4:]=sc.fit_transform(x[:,-4:])

In [15]:
print(x[:,-4:])

[[1.892524165060669 -0.594371334523968 0.16134171317008306
  0.29855522291351505]
 [0.7983890791108927 1.1632791845925685 1.2397527781558477
  0.2711804434150313]
 [1.892524165060669 -0.594371334523968 -0.9170693518156816
  0.4442607456965164]
 ...
 [0.7983890791108927 -0.594371334523968 -0.9170693518156816
  -0.6809730477840181]
 [-1.3898810927886598 -0.594371334523968 -0.9170693518156816
  0.47000607403437616]
 [0.7983890791108927 -0.594371334523968 -0.9170693518156816
  2.0889961582072063]]


In [29]:
#Q2. C
test = dataset.iloc[:, [0, 10,16, 17, 18, 19, 20, 21, 22]].values
df_test = pd.DataFrame(test)
col_name = df_test.columns[1]


# Get value counts
city_counts = df_test[col_name].value_counts()

# Keep top N cities, rest as 'Other'
top_N = 3
top_cities = city_counts.nlargest(top_N).index

df_test[col_name] = df_test[col_name].apply(lambda x: x if x in top_cities else "Other")

In [33]:
print(df_test)

           0               1  2  3  4  5  6  7       8
0      21173       Australia  M  M  1  3  0  1   81916
1      13249           Other  M  M  1  2  1  2   81076
2      29350   United States  F  S  0  3  0  0   86387
3      13503  United Kingdom  M  M  1  2  1  2   61481
4      22803           Other  M  S  1  1  0  0   51804
...      ...             ... .. .. .. .. .. ..     ...
18356  25414   United States  F  M  0  1  0  2   52953
18357  11459       Australia  F  S  0  2  0  0   60992
18358  12160   United States  F  S  0  2  0  0   51859
18359  14353           Other  F  S  0  0  0  0   87177
18360  16676   United States  F  M  1  2  0  0  136856

[18361 rows x 9 columns]


In [35]:
# Pick two objects
obj1_cat = x_transformed[0]   # one-hot encoded categorical part
obj2_cat = x_transformed[1]

obj1_num = x[0, -4:]  # standardized numerical part (last 4 cols)
obj2_num = x[1, -4:]

# --- Simple Matching (on categorical part) ---
def simple_matching(x, y):
    matches = np.sum(x == y)
    return matches / len(x)

smc = simple_matching(obj1_cat, obj2_cat)

# --- Jaccard (on categorical part) ---
def jaccard_similarity(x, y):
    intersection = np.sum((x == 1) & (y == 1))
    union = np.sum((x == 1) | (y == 1))
    return intersection / union if union != 0 else 0

jacc = jaccard_similarity(obj1_cat, obj2_cat)

# --- Cosine (on standardized numerical part) ---
from sklearn.metrics.pairwise import cosine_similarity
cos_sim = cosine_similarity([obj1_num], [obj2_num])[0][0]

print("Simple Matching Coefficient:", smc)
print("Jaccard Similarity:", jacc)
print("Cosine Similarity (standardized numeric):", cos_sim)


Simple Matching Coefficient: 0.5882352941176471
Jaccard Similarity: 0.42857142857142855
Cosine Similarity (standardized numeric): 0.2881711261100598
